/**
 * This class is generated by jOOQ
 */
package com.jooq.database;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table UserSolutionResults
	 */
	public static final com.jooq.database.tables.Usersolutionresults USERSOLUTIONRESULTS = com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS;
}
