/**
 * This class is generated by jOOQ
 */
package com.jooq.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usersolutionresults extends org.jooq.impl.TableImpl<com.jooq.database.tables.records.UsersolutionresultsRecord> {

	private static final long serialVersionUID = -1076234548;

	/**
	 * The singleton instance of <code>UserSolutionResults</code>
	 */
	public static final com.jooq.database.tables.Usersolutionresults USERSOLUTIONRESULTS = new com.jooq.database.tables.Usersolutionresults();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooq.database.tables.records.UsersolutionresultsRecord> getRecordType() {
		return com.jooq.database.tables.records.UsersolutionresultsRecord.class;
	}

	/**
	 * The column <code>UserSolutionResults.name</code>.
	 */
	public final org.jooq.TableField<com.jooq.database.tables.records.UsersolutionresultsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>UserSolutionResults.passed</code>.
	 */
	public final org.jooq.TableField<com.jooq.database.tables.records.UsersolutionresultsRecord, java.lang.String> PASSED = createField("passed", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>UserSolutionResults.error</code>.
	 */
	public final org.jooq.TableField<com.jooq.database.tables.records.UsersolutionresultsRecord, java.lang.String> ERROR = createField("error", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>UserSolutionResults.timestamp</code>.
	 */
	public final org.jooq.TableField<com.jooq.database.tables.records.UsersolutionresultsRecord, java.lang.String> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>UserSolutionResults</code> table reference
	 */
	public Usersolutionresults() {
		this("UserSolutionResults", null);
	}

	/**
	 * Create an aliased <code>UserSolutionResults</code> table reference
	 */
	public Usersolutionresults(java.lang.String alias) {
		this(alias, com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS);
	}

	private Usersolutionresults(java.lang.String alias, org.jooq.Table<com.jooq.database.tables.records.UsersolutionresultsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Usersolutionresults(java.lang.String alias, org.jooq.Table<com.jooq.database.tables.records.UsersolutionresultsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooq.database.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooq.database.tables.Usersolutionresults as(java.lang.String alias) {
		return new com.jooq.database.tables.Usersolutionresults(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooq.database.tables.Usersolutionresults rename(java.lang.String name) {
		return new com.jooq.database.tables.Usersolutionresults(name, null);
	}
}
