/**
 * This class is generated by jOOQ
 */
package com.jooq.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersolutionresultsRecord extends org.jooq.impl.TableRecordImpl<com.jooq.database.tables.records.UsersolutionresultsRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -199005406;

	/**
	 * Setter for <code>UserSolutionResults.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>UserSolutionResults.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>UserSolutionResults.passed</code>.
	 */
	public void setPassed(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>UserSolutionResults.passed</code>.
	 */
	public java.lang.String getPassed() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>UserSolutionResults.error</code>.
	 */
	public void setError(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>UserSolutionResults.error</code>.
	 */
	public java.lang.String getError() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>UserSolutionResults.timestamp</code>.
	 */
	public void setTimestamp(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>UserSolutionResults.timestamp</code>.
	 */
	public java.lang.String getTimestamp() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS.PASSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS.ERROR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPassed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getError();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersolutionresultsRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersolutionresultsRecord value2(java.lang.String value) {
		setPassed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersolutionresultsRecord value3(java.lang.String value) {
		setError(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersolutionresultsRecord value4(java.lang.String value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersolutionresultsRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersolutionresultsRecord
	 */
	public UsersolutionresultsRecord() {
		super(com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS);
	}

	/**
	 * Create a detached, initialised UsersolutionresultsRecord
	 */
	public UsersolutionresultsRecord(java.lang.String name, java.lang.String passed, java.lang.String error, java.lang.String timestamp) {
		super(com.jooq.database.tables.Usersolutionresults.USERSOLUTIONRESULTS);

		setValue(0, name);
		setValue(1, passed);
		setValue(2, error);
		setValue(3, timestamp);
	}
}
